### ISSUE TITLE
Incompatible with the QuickRestart mod

### ISSUE THREAD

**Issue by ghost** [Mordrog/RoR2-PlayerRespawnSystem#1]
https://thunderstore.io/package/AceOfShades/QuickRestart/

After the console says "Accepting vote from PlayerName" usually it'd just start but with this mod for some reason it just spews error messages:

"NullReferenceException: Object reference not set to an instance of an object"
"Instance not found when handling Command message [netId=(randomnumber]"

No idea how these 2 mods interfere with each other

**Comment by Maceris** [comment]
I feel like this has something to do with QuickRestart destroying the Run instance: https://github.com/Maceris/quick-restart/blob/v1.3.1/BoothUtil.cs#L145

But QuickRestart is a client side (only) mod, and PlayerRespawnSystem is tagged as server-side, would both be installed for single player?

**Comment by ghost** [comment]
I just use r2modman and play and host ingame normally. I'm not sure why the Respawn mod would be loaded in Singlerplayer but the Restart mod already does not work in multiplayer

**Comment by Mordrog** [comment]
Outdated
